services:
  - type: web
    name: earneasyv5
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: GOOGLE_SPREADSHEET_ID
        value: 1WzGkrTgEjchqgC2_ZImeyd-mFoiCobmU-MmTG3KXzDQ
